plugins:
  legacy_info_enabled:
    default: true
    client: true
  min_trust_level:
    default: 4
    client: 4
  enable_for_guests:
    default: true
    client: true
  enable_hide_canonical:
    default: false
    client: false
